x-common: &common
  env_file:
    - .env
  restart: unless-stopped

services:
  bot:
    <<: [*common]
    container_name: currentinfo-bot
    build:
      context: .
    volumes:
      - .:/app
    network_mode: host
